name: snakemake2
channels:
  - bioconda
  - conda-forge
  - mamba
dependencies:
  - trim-galore = 0.6.7
  - unicycler = 0.4.4
  - umi_tools = 1.1.2
  - samtools = 1.14
  - assembly-stats = 1.0.1
  - seqtk = 1.3
  - bwa = 0.7.17
  - python = 3.8
  - bcftools = 1.14
  - nanostat = 1.1.2
  - porechop = 0.2.4
  - fastqc = 0.11.9
  - kraken2 = 2.1.2
  - multiqc = 1.12

